RSApp.Presentation.WebApp/Controllers/UpgradeController.cs
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Services;
using RSApp.Core.Services.ViewModels.SaveVm;

namespace RSApp.Presentation.WebApp.Controllers;

public class UpgradeController : Controller {
  private readonly IUpgradeService _upgradeService;

  public UpgradeController(IUpgradeService upgradeService) {
    _upgradeService = upgradeService;
  }
  public IActionResult Index() {
    return View();
  }

  public IActionResult Create() => View(new SaveUpgradeVm());

  [HttpPost]
  public async Task<IActionResult> Create(SaveUpgradeVm model) {
    if (!ModelState.IsValid)
      return View(model);
    try {
      await _upgradeService.Create(model);
      return RedirectToAction("Index");
    } catch (Exception ex) {
      model.HasError = true;
      model.ErrorMessage = ex.Message;
      return View(model);
    }
  }

  public async Task<IActionResult> Edit(int id) {
    var model = await _upgradeService.GetEntity(id);
    return View(model);
  }

  [HttpPost]
  public async Task<IActionResult> Edit(SaveUpgradeVm model) {
    if (!ModelState.IsValid)
      return View(model);
    try {
      await _upgradeService.Edit(model);
      return RedirectToAction("Index");
    } catch (Exception ex) {
      model.HasError = true;
      model.ErrorMessage = ex.Message;
      return View(model);
    }
  }

  public async Task<IActionResult> Delete(int id) {
    var model = await _upgradeService.GetEntity(id);
    if (model != null) {
      try {
        await _upgradeService.Delete(id);
        return RedirectToAction("Index");
      } catch (Exception ex) {
        model.HasError = true;
        model.ErrorMessage = ex.Message;
      }
    }
    return RedirectToAction("Index");
  }
}

RSApp.Presentation.WebApp/ViewComponents/UpgradeListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Services;

namespace RSApp.Presentation.WebApp.ViewComponents;

public class UpgradeListViewComponent : ViewComponent {
  private readonly IUpgradeService _upgradeService;

  public UpgradeListViewComponent(IUpgradeService upgradeService) {
    _upgradeService = upgradeService;
  }

  public async Task<IViewComponentResult> InvokeAsync() {
    var upgrades = await _upgradeService.GetAll();
    return View(upgrades);
  }
}

RSApp.Presentation.WebApp/Views/Upgrade/Create.cshtml
@using RSApp.Core.Services.ViewModels.SaveVm;
@model SaveUpgradeVm;

@{
  ViewData["Title"] = "Create Property";
}

<div class="row text-lg">
  <div class="col-md-5">
    <h2 class="text-3xl mb-3">Create Upgrade</h2>
  @if (Model.HasError)
    {
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p>@Model.ErrorMessage</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    }
  <form asp-action="Create">
    <div class="form-group mb-3">
      <label asp-for="Name" class="control-label"></label>
      <input asp-for="Name" class="form-control" />
      <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
      <label asp-for="Description" class="control-label"></label>
      <input asp-for="Description" class="form-control" />
      <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="btn-group mb-3 col-12">
      <a asp-action="Index" asp-controller="Home" class="btn btn-outline-primary w-full">Back</a>
      <input type="submit" class="btn w-25 btn-outline-success w-100" value="Create" />
    </div>
  </form>
  </div>
</div>

RSApp.Presentation.WebApp/Views/Upgrade/Edit.cshtml
@using RSApp.Core.Services.ViewModels.SaveVm;
@model SaveUpgradeVm;

@{
  ViewData["Title"] = "Edit Property Type";
}

<div class="row text-lg">
  <div class="col-md-5">
    <h2 class="text-3xl mb-3">Editing: @Model.Name</h2>
  @if (Model.HasError)
    {
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p>@Model.ErrorMessage</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    }
  <form asp-action="Edit">
    <div class="form-group mb-3">
      <label asp-for="Name" class="control-label"></label>
      <input asp-for="Name" class="form-control" />
      <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group mb-3">
      <label asp-for="Description" class="control-label"></label>
      <input asp-for="Description" class="form-control" />
      <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="btn-group mb-3 col-12">
          <a asp-action="Index" asp-controller="Home" class="btn btn-outline-primary w-full">Back</a>
          <input type="submit" class="btn w-25 btn-outline-success w-100" value="Edit" />
        </div>
  </form>
  </div>
</div>

RSApp.Presentation.WebApp/Views/Upgrade/Index.cshtml
@{
  ViewData["Title"] = "Types";
}
<div class="row">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="font-monospace text-2xl">Upgrades</h1>
    <a asp-action="Create" class="btn btn-outline-primary">Create</a>
  </div>
  <hr class="my-3 " />
  @await Component.InvokeAsync("UpgradeList")
</div>