RSApp.Presentation.WebApp/Controllers/AdminUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Contracts;
using RSApp.Core.Services.Dtos.Account;
using RSApp.Core.Services.ViewModels.SaveVm;
using RSApp.Presentation.WebApp.helpers;
using RSApp.Presentation.WebApp.Middleware;

namespace RSApp.Presentation.WebApp.Controllers;

[Authorize(Roles = "Admin")]
public class AdminUserController : Controller {
  private readonly IUserService _userService;

  public AdminUserController(IUserService userService) {
    _userService = userService;
  }
  public IActionResult Index() => View();

  public async Task<IActionResult> ChangeStatus(string id) {
    var userIsVerify = await _userService.GetById(id);

    await _userService.ChangeStatus(userIsVerify.Id);

    return View("Index");
  }

  public IActionResult Agents() => View();
  public IActionResult Clients() => View();
  public IActionResult Developers() => View();
  public IActionResult Admins() => View();

  public async Task<IActionResult> Edit(string id) => View(await _userService.GetEntity(id));

  [HttpPost]
  public async Task<IActionResult> Edit(SaveUserVm model) {
    if (!ModelState.IsValid)
      return View(model);

    try {
      var user = await _userService.GetEntity(model.Id);
      user.Image = ManageFile.Upload(model.ImageFile, model.Id, true, user.Image);
      await _userService.UpdateUserAsync(user);
      return RedirectToRoute(new { controller = "AdminUser", action = "Index" });
    } catch (Exception ex) {
      model.HasError = true;
      model.Error = ex.Message;
      return View(model);
    }
  }
}

RSApp.Presentation.WebApp/Controllers/AgentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Contracts;
using RSApp.Core.Services.Dtos.Account;
using RSApp.Core.Services.Helpers;
using RSApp.Core.Services.Services;
using RSApp.Core.Services.ViewModels.SaveVm;
using RSApp.Presentation.WebApp.helpers;

namespace RSApp.Presentation.WebApp.Controllers;

[Authorize(Roles = "Agent")]
public class AgentController : Controller
{
  private readonly IPropertyService _propertyService;
  private readonly IPropTypeService _propTypeService;
  private readonly ISaleService _saleService;
  private readonly IImageService _imageService;
  private readonly IUpgradeService _upgradeService;
  private readonly IUserService _userService;
  private readonly IPropUpgradeService _propUpgradeService;
  private readonly IHttpContextAccessor _httpContextAccessor;
  private readonly AuthenticationResponse? _currentUser;

  public AgentController(IPropertyService propertyService, IPropTypeService propTypeService, ISaleService saleService, IHttpContextAccessor httpContextAccessor, IImageService imageService, IUpgradeService upgradeService, IPropUpgradeService propUpgradeService, IUserService userService)
  {
    _propertyService = propertyService;
    _propTypeService = propTypeService;
    _saleService = saleService;
    _httpContextAccessor = httpContextAccessor;
    _imageService = imageService;
    _upgradeService = upgradeService;
    _propUpgradeService = propUpgradeService;
    _userService = userService;
    _currentUser = _httpContextAccessor.HttpContext?.Session.Get<AuthenticationResponse>("user");
  }
  public IActionResult Index() => View();
  public IActionResult OwnProperty() => View();
  public async Task<IActionResult> Create() => View(new SavePropertyVm()
  {
    Types = await _propTypeService.GetAll(),
    Sales = await _saleService.GetAll(),
    Upgrades = await _upgradeService.GetAll()
  });

  [HttpPost]
  public async Task<IActionResult> Create(SavePropertyVm model)
  {
    if (!ModelState.IsValid)
      return View(await Error(model));

    model.Agent = _currentUser.Id;
    model.Code = Guid.NewGuid().ToString()[..8].Replace("-", "").ToUpper();

    var created = await _propertyService.Create(model);
    if (created.Id != 0)
    {
      created.Portrait = ManageFile.UploadProperty(model.ImageFile, _currentUser.Id, created.Id);

      await _propertyService.Edit(created);
      if (model.ImageFiles != null)
      {
        foreach (var image in model.ImageFiles)
        {
          var img = new SaveImageVm()
          {
            PropertyId = created.Id,
            ImagePath = ManageFile.UploadPropertyImages(image, _currentUser.Id, created.Id)
          };
          await _imageService.Create(img);
        }
      }
    }

    var upgrades = await _upgradeService.GetAll();
    var validateUpgrades = upgrades.Where(x => model.UpgradeId.Contains(x.Id)).ToList();

    List<SavePropUpgradeVm> propertyUpgrades = new();

    foreach (var upgrade in validateUpgrades)
    {
      propertyUpgrades.Add(new SavePropUpgradeVm()
      {
        PropertyId = created.Id,
        UpgradeId = upgrade.Id,
      });
    }

    await _propUpgradeService.SaveRange(propertyUpgrades);

    return RedirectToAction("OwnProperty");
  }

  public async Task<IActionResult> Edit(int id)
  {
    var property = await _propertyService.GetEntity(id);
    property.Sales = await _saleService.GetAll();
    property.Types = await _propTypeService.GetAll();
    property.Upgrades = await _upgradeService.GetAll();
    return View(property);
  }

  [HttpPost]
  public async Task<IActionResult> Edit(SavePropertyVm model)
  {
    if (!ModelState.IsValid)
      return View(model);

    var entity = await _propertyService.GetEntity(model.Id);
    model.Agent = entity.Agent;
    model.Code = entity.Code;

    model.Portrait = ManageFile.UploadProperty(model.ImageFile, _currentUser.Id, model.Id, true, entity.Portrait);

    await _propertyService.Edit(model);

    if (model.UpgradeId != null) {
      var upgrades = await _upgradeService.GetAll();
      var validateUpgrades = upgrades.Where(x => model.UpgradeId.Contains(x.Id)).ToList();
      var propUpgrades = await _propUpgradeService.GetAll().ContinueWith(x => x.Result.Where(y => y.PropertyId == model.Id).ToList());

      List<SavePropUpgradeVm> propertyUpgrades = new();

      foreach (var upgrade in validateUpgrades)
      {
        propertyUpgrades.Add(new SavePropUpgradeVm()
        {
          PropertyId = model.Id,
          UpgradeId = upgrade.Id,
        });
      }
      propertyUpgrades = propertyUpgrades.Where(x => !propUpgrades.Select(y => y.UpgradeId).Contains(x.UpgradeId)).ToList();

      await _propUpgradeService.SaveRange(propertyUpgrades);
    }

    return RedirectToAction("OwnProperty");
  }

  public async Task<IActionResult> Delete(int id)
  {
    var property = await _propertyService.GetEntity(id);
    if (property != null)
      await _propertyService.Delete(id);

    return RedirectToAction("OwnProperty");
  }

  private async Task<SavePropertyVm> Error(SavePropertyVm model)
  {
    model.Types = await _propTypeService.GetAll();
    model.Sales = await _saleService.GetAll();
    model.Upgrades = await _upgradeService.GetAll();
    return model;
  }

}

RSApp.Presentation.WebApp/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RSApp.Presentation.WebApp.Controllers;
[Authorize(Roles = "Client")]
public class ClientController : Controller
{
  public IActionResult Index()
  {
    return View();
  }
}

RSApp.Presentation.WebApp/ViewComponents/UserListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Contracts;
using RSApp.Core.Services.Dtos.Account;
using RSApp.Core.Services.Helpers;

namespace RSApp.Presentation.WebApp.ViewComponents;

public class UserListViewComponent : ViewComponent {
  private readonly IUserService _userService;
  private readonly IHttpContextAccessor _httpContextAccessor;
  private readonly AuthenticationResponse? _currentUser;

  public UserListViewComponent(IUserService userService, IHttpContextAccessor httpContextAccessor) {
    _userService = userService;
    _httpContextAccessor = httpContextAccessor;
    _currentUser = _httpContextAccessor.HttpContext?.Session.Get<AuthenticationResponse>("user");
  }

  public async Task<IViewComponentResult> InvokeAsync(string role) {
    
    var users = await _userService.GetAll().ContinueWith(x => x.Result.Where(us => us.Id != _currentUser.Id ));
    if (role != null)
      users = users.Where(us => us.Role == role);
    return View(users);
  }
}

RSApp.Presentation.WebApp/Views/AdminUser/Admin.cshtml
@{
    ViewData["Title"] = "Users";
}

<div class="row">
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="font-monospace text-2xl">Agents users</h1>
        <a asp-action="Create" class="btn btn-outline-primary">Create</a>
    </div>
    <hr class="my-3 " />
    @await Component.InvokeAsync("UserList", new { role = "Admin" });
</div>

RSApp.Presentation.WebApp/Views/AdminUser/Agents.cshtml
@{
    ViewData["Title"] = "Users";
}

<div class="row">
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="font-monospace text-2xl">Agents users</h1>
        <a asp-action="Create" class="btn btn-outline-primary">Create</a>
    </div>
    <hr class="my-3 " />
    @await Component.InvokeAsync("UserList", new { role = "Agent" });
</div>

RSApp.Presentation.WebApp/Views/AdminUser/Clients.cshtml
@{
  ViewData["Title"] = "Users";
}

<div class="row">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="font-monospace text-2xl">Client users</h1>
    <a asp-action="Create" class="btn btn-outline-primary">Create</a>
  </div>
  <hr class="my-3 " />
  @await Component.InvokeAsync("UserList", new { role = "Client" });
</div>

RSApp.Presentation.WebApp/Views/AdminUser/Create.cshtml
@model RSApp.Core.Services.ViewModels.SaveVm.SaveUserVm
@using RSApp.Core.Services.Dtos.Account
@using Microsoft.AspNetCore.Http;
@using RSApp.Core.Services.Helpers;
@inject IHttpContextAccessor _httpContext;
@{
  ViewData["Title"] = "Home Page";
  AuthenticationResponse user = _httpContext.HttpContext.Session.Get<AuthenticationResponse>("user");
}

@{
  ViewData["Title"] = "Sign Up";
}

<h1 class="text-4xl mb-3">Sign Up</h1>

<hr />
<div class="row">
  <div class="col-md-4">
    @if (Model.HasError)
    {
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p>@Model.Error</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    }
    <form asp-action="Create" enctype="multipart/form-data">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="FirstName" class="text-lg ">First Name</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="LastName" class="text-lg">Last Name</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="ImageFile" class="text-lg">Image</label>
        <input asp-for="ImageFile" class="form-control"  required />
        <span asp-validation-for="ImageFile" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Email" class="text-lg"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="PhoneNumber" class="text-lg">Phone </label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="DNI" class="text-lg"></label>
        <input asp-for="DNI" class="form-control" />
        <span asp-validation-for="DNI" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="UserName" class="text-lg"></label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Password" class="text-lg"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>
      <div class="form-group mb-3">
        <label asp-for="ConfirmPassword" class="text-lg"> Confirm Password</label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
      </div>
      <div class="form-group mb-3">
        <label asp-for="Role" class="text-lg"></label>
        <select asp-for="Role" class="form-control">
          @if (user != null && user.Roles.Contains("Admin"))
          {
            <option value="1">Admin</option>
            <option value="2">Developer</option>
            <option value="3">Agent</option>
          }
          <option value="4">Client</option>
        </select>
        <span asp-validation-for="Role" class="text-danger"></span>
      </div>
      <div>
        <div class="btn-group mb-3 col-12">
          <a asp-action="Index" asp-controller="Home" class="btn btn-outline-primary w-full">Back</a>
          <input type="submit" class="btn w-25 btn-outline-success w-100" value="Create" />
        </div>
      </div>
    </form>
  </div>
</div>

@section Scripts {
@{
await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

}

RSApp.Presentation.WebApp/Views/AdminUser/Developers.cshtml
@{
  ViewData["Title"] = "Users";
}

<div class="row">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="font-monospace text-2xl">Developer users</h1>
    <a asp-action="Create" class="btn btn-outline-primary">Create</a>
  </div>
  <hr class="my-3 " />
  @await Component.InvokeAsync("UserList", new { role = "Dev" });
</div>

RSApp.Presentation.WebApp/Views/AdminUser/Edit.cshtml
@model RSApp.Core.Services.ViewModels.SaveVm.SaveUserVm

@{
  ViewData["Title"] = "Sign Up";
}

<h1>Editing: @Model.UserName</h1>

<hr />
<div class="row">
  <div class="col-md-4">
    @if (Model.HasError)
    {
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p>@Model.Error</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    }
    <form asp-action="Edit">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="FirstName" class="control-label">First Name</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="LastName" class="control-label">Last Name</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Phone </label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="DNI" class="control-label"></label>
        <input asp-for="DNI" class="form-control" />
        <span asp-validation-for="DNI" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="UserName" class="control-label"></label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>
      <div class="form-group mb-3">
        <label asp-for="ConfirmPassword" class="control-label"> Confirm Password</label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
      </div>
      <div>
        <div class="btn-group mb-3 col-12">
          <a asp-action="Index" asp-controller="Home" class="btn btn-outline-primary w-full">Back</a>
          <input type="submit" class="btn w-25 btn-outline-prinary w-100" value="Edit" />
        </div>
      </div>
    </form>
  </div>
</div>
@section Scripts {
@{
await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

RSApp.Presentation.WebApp/Views/AdminUser/Index.cshtml
@using RSApp.Core.Services.Dtos.Account
@using Microsoft.AspNetCore.Http;
@using RSApp.Core.Services.Helpers;
@inject IHttpContextAccessor _httpContext;
@model AccountDto
@{
  ViewData["Title"] = "Users";
  AuthenticationResponse user = _httpContext.HttpContext.Session.Get<AuthenticationResponse>("user");
}

<div class="row">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="font-monospace text-2xl">Welcome @user.UserName</h1>
    <a asp-action="Create" asp-controller="Profile" class="btn btn-outline-primary">Create</a>
  </div>
  <hr class="my-3 " />
  @await Component.InvokeAsync("UserList")
</div>