RSApp.Presentation.WebApp/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RSApp.Presentation.WebApp.Controllers;
[Authorize(Roles = "Client")]
public class ClientController : Controller
{
  public IActionResult Index()
  {
    return View();
  }
}

RSApp.Presentation.WebApp/ViewComponents/PropertyListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Services;

namespace RSApp.Presentation.WebApp.ViewComponents;

public class PropertyListViewComponent : ViewComponent
{
  private readonly IPropertyService _propertyService;
  private readonly IFavoriteService _favoriteService;

  public PropertyListViewComponent(IPropertyService propertyService, IFavoriteService favoriteService)
  {
    _propertyService = propertyService;
    _favoriteService = favoriteService;
  }

  public async Task<IViewComponentResult> InvokeAsync(bool isFavorite = false){
    var favorites = await _favoriteService.GetAll();
    var properties = await _propertyService.GetAll();
    if (isFavorite)
      properties = properties.Where(p => favorites.Any(f => f.PropertyId == p.Id)).ToList();
    return View(properties);
  }
}

RSApp.Presentation.WebApp/Views/Client/Index.cshtml
@{
  ViewData["Title"] = "Favorite Properties";
}
<div class="row">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="font-monospace text-2xl">Favorites</h1>
  </div>
  <hr class="my-3 " />
  @await Component.InvokeAsync("PropertyList", new { isFavorite = true })
</div>