RSApp.Presentation.WebApp/Controllers/TypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RSApp.Core.Services.Services;
using RSApp.Core.Services.ViewModels.SaveVm;

namespace RSApp.Presentation.WebApp.Controllers;
[Authorize(Roles = "Admin")]
public class TypeController : Controller {
  private readonly IPropTypeService _typeService;

  public TypeController(IPropTypeService typeService) {
    _typeService = typeService;
  }
  public IActionResult Index() {
    return View();
  }

  public IActionResult Create() => View(new SavePropTypeVm());

  [HttpPost]
  public async Task<IActionResult> Create(SavePropTypeVm model) {
    if (!ModelState.IsValid)
      return View(model);
    try {
      await _typeService.Create(model);
      return RedirectToAction("Index");
    } catch (Exception ex) {
      model.HasError = true;
      model.ErrorMessage = ex.Message;
      return View(model);
    }
  }

  public async Task<IActionResult> Edit(int id) {
    var model = await _typeService.GetEntity(id);
    return View(model);
  }

  [HttpPost]
  public async Task<IActionResult> Edit(SavePropTypeVm model) {
    if (!ModelState.IsValid)
      return View(model);
    try {
      await _typeService.Edit(model);
      return RedirectToAction("Index");
    } catch (Exception ex) {
      model.HasError = true;
      model.ErrorMessage = ex.Message;
      return View(model);
    }
  }

  public async Task<IActionResult> Delete(int id) {
    var model = await _typeService.GetEntity(id);
    if (model != null) {
      try {
        await _typeService.Delete(id);
        return RedirectToAction("Index");
      } catch (Exception ex) {
        model.HasError = true;
        model.ErrorMessage = ex.Message;
      }
    }
    return RedirectToAction("Index");
  }
}

RSApp.Presentation.WebApp/Views/Shared/Components/SaleList/Default.cshtml
@using RSApp.Core.Services.ViewModels;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor _httpContext;
@model IEnumerable<SaleVm>



<div class="row">
  @if (Model.Count() != 0)
  {
    <table class="table table-dark table-striped table-hover text-start">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Description
          </th>
          <th>
            Actions
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach (var item in Model)
        {
          <tr>
            <td>
              @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
              @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
              <a asp-action="Edit" class="btn btn-outline-info" asp-route-id="@item.Id"><i
              class="bi bi-pencil-square"></i></a>
            </td>
            <td>
              <a asp-action="Delete" asp-controller="Type" asp-route-id="@item.Id" onclick="return  confirm('Are you sure you want to delete this sale type: @item.Name?')" class="btn btn-outline-danger mb-3"><i
              class="bi bi-trash-fill"></i></a>
            </td>
          </tr>
        }
      </tbody>
    </table>
  }
  else
  {
    <div class="alert alert-warning" role="alert">
      No Sales Created
    </div>
  }
</div>